#!/bin/sh
# for now not used - contents from ubuntu actually
if [ "$METHOD" = loopback ]; then
    exit 0
fi

if [ "$MODE" != start ]; then
    exit 0
fi

/bin/bash /opt/websafety/bin/va_issue.sh > /etc/issue